apiVersion: v1
kind: Service
metadata:
  name: aperture
  labels:
    app: aperture
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
    - port: 9001
      targetPort: 9001
      protocol: TCP
  selector:
    app: aperture
