apiVersion: apps/v1
kind: Deployment
metadata:
  name: aperture
  labels:
    app: aperture
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aperture
  template:
    metadata:
      labels:
        app: aperture
    spec:
      containers:
        - image: registry.example.com/cryb/aperture:latest
          name: aperture
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: aperture-env-secret
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 4000
              name: http-server
      imagePullSecrets:
        - name: registry-regcred-aperture
