apiVersion: v1
kind: Secret
metadata:
  name: aperture-env-secret
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # Port which aperture should listen on
  APERTURE_PORT: "9001"
  # This should the same secure key in api/api.env.secret.yml under 'APERTURE_WS_KEY'
  APERTURE_KEY: "api-aperture-key"
  # Port which streaming should listen to
  STREAMING_PORT: "9000"
  # This should be the same secure key in portal/portal.env.secret.yml under 'STREAMING_KEY'
  STREAMING_KEY: "portal-streaming-key"

  # The URI used for connecting to the MongoDB database
  MONGO_URI: "mongodb://"

  # The Sentry.io DSN used for error tracking
  SENTRY_DSN: ""
