apiVersion: v1
kind: Secret
metadata:
  name: api-env-secret
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # The JWT key used to encrypt/decrypt tokens used for user authentication
  JWT_KEY: "jwt-key"

  # The URI used for connecting to the MongoDB database
  MONGODB_URI: "mongodb://""