apiVersion: v1
kind: ServiceAccount
metadata:
  name: portals-serviceaccount
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: portals-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create","delete","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: portals-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: portals-clusterrole
subjects:
- kind: ServiceAccount
  name: portals-serviceaccount
  namespace: default