apiVersion: v1
kind: Secret
metadata:
  name: portals-env-secret
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # The URI used for connecting to the MongoDB database
  MONGO_URI: "mongodb://"
  # The URI used for connecting to the redis-ha sentinel instance
  REDIS_SENTINELS: "redis-sentinel://"

  # The base REST endpoint that is used to talk to @cryb/api
  API_URL: "http://api"
  # This should the same secure key in api/api.env.secret.yml under 'PORTALS_API_KEY'
  API_KEY: "api-portals-key"

  # This should be the same secure key in portal/portal.env.secret.yml under ''
  PORTAL_KEY: "portals-portal-key"

  # The Sentry.io DSN used for error tracking
  SENTRY_DSN: ""