apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # If you are using DigitalOcean Kubernetes, please uncomment the line below
  # storageClassName: do-block-storage