apiVersion: v1
kind: Secret
metadata:
  name: portal-env-secret
  namespace: portals
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # The base WebSocket endpoint that is used to talk to @cryb/portals
  PORTALS_WS_URL: "https://portals.example.com"
  # This should the same secure key in portal/portal.env.secret.yml under 'PORTAL_KEY'
  PORTALS_KEY: "portals-portal-key"

  # The URL of @cryb/aperture streaming that ffmpeg should stream to. This should be :9000 on @cryb/aperture.
  STREAMING_URL: "http://aperture.example.com:9000"
  # This should the same secure key in aperture/aperture.env.secret.yml under 'STREAMING_KEY'
  STREAMING_KEY: "portal-streaming-key"

  # The Display services like Chromium and ffmpeg will use
  DISPLAY: ":100"
  # The width/height of the video being sent. This is the config used for a 720p stream.
  VIDEO_WIDTH: "1280"
  VIDEO_HEIGHT: "720"
  # The bitrate of the video stream in kilobits
  VIDEO_BITRATE: "900k"
  # The Frames Per Second of the video stream (the lower it is, the higher performance is)
  VIDEO_FPS: "30"
  # Switch to false if you want to disable audio support (could result in better performance)
  AUDIO_ENABLED: "true"
  # The bitrate of the audio stream in kilobits
  AUDIO_BITRATE: "128k"

  # Used to configure Chromium Dark Mode
  IS_CHROMIUM_DARK_MODE: "true"

  # URL that will be used on first start
  STARTUP_URL: "https://www.google.com"
  
  # The Sentry.io DSN used for error tracking
  SENTRY_DSN: ""
