apiVersion: v1
kind: Secret
metadata:
  name: portal-env-secret
  namespace: portals
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # This should the same secure key in portal/portal.env.secret.yml under 'PORTAL_KEY'
  PORTALS_KEY: "portals-portal-key"
  # The base WebSocket endpoint that is used to talk to @cryb/portals
  PORTALS_WS_URL: "https://portals.example.com"

  # The width/height of the video being sent. This is the config used for a 720p stream.
  VIDEO_WIDTH: "1280"
  VIDEO_HEIGHT: "720"
  
  # The Sentry.io DSN used for error tracking
  SENTRY_DSN: "https://6cbdaa327a7043d38076f2e6f9582a0c@sentry.io/1547927"