apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas
  labels:
    app: atlas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: atlas
  template:
    metadata:
      labels:
        app: atlas
    spec:
      containers:
        - image: registry.example.com/cryb/atlas:latest
          name: atlas
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: atlas-env-secret
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 5500
              name: http-server
      imagePullSecrets:
        - name: registry-regcred-atlas
