apiVersion: v1
kind: Secret
metadata:
  name: api-env-secret
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # Port which @cryb/api should listen on
  PORT: "4000"

  # The JWT key used to encrypt/decrypt tokens used for user authentication
  JWT_KEY: "jwt-key"

  # The base REST endpoint that is used to talk to @cryb/portals
  PORTALS_API_URL: "http://portals.example.com:9001"
  # This should the same secure key in portals/portals.env.secret.yml under 'API_KEY'
  PORTALS_API_KEY: "api-portals-key"

  # The base WS endpoint that is used to talk to @cryb/aperture which is sent to the client via WS once the stream is ready
  APERTURE_WS_URL: "ws://aperture.example.com:9001"
  # This should the same secure key in aperture/aperture.env.secret.yml under 'APERTURE_WS_KEY'
  APERTURE_WS_KEY: "api-aperture-key"

  # The URI used for connecting to the MongoDB database
  MONGO_URI: "mongodb://"
  # The URI used for connecting to the redis-ha sentinel instance
  REDIS_SENTINELS: "redis-sentinel://"

  # The Discord Developer Application credentials.
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  DISCORD_CALLBACK_URL: "https://example.com/auth/discord"

# This should be a list of comma-separated (not space) Oauth2 Redirect URLs
  DISCORD_OAUTH_ORIGINS: "https://example.com"

  # The Sentry.io DSN used for error tracking
  SENTRY_DSN: ""
