apiVersion: v1
kind: Secret
metadata:
  name: api-env-secret
type: Opaque
stringData:
  # The environment the app is running in, either production, staging or development
  NODE_ENV: "production"

  # The JWT key used to encrypt/decrypt tokens used for user authentication
  JWT_KEY: "jwt-key"

  # The base REST endpoint that is used to talk to @cryb/portals
  PORTALS_API_URL: "http://portals"
  # This should the same secure key in portals/portals.env.secret.yml under 'API_KEY'
  PORTALS_API_KEY: "api-portals-key"
  
  # The URI used for connecting to the MongoDB database
  MONGO_URI: "mongodb://"
  # The URI used for connecting to the redis-ha sentinel instance
  REDIS_SENTINELS: "redis-sentinel://"

  # The Discord Developer Application credentials.
  DISCORD_CLIENT_ID: ""
  DISCORD_CLIENT_SECRET: ""
  DISCORD_CALLBACK_URL: "https://example.com/auth/discord"

  # The Sentry.io DSN used for error tracking
  SENTRY_DSN: ""
