apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - image: registry.example.com/cryb/web:latest
          name: web
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: web-env-secret
          env:
            - name: K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 4000
              name: http-server
      imagePullSecrets:
        - name: registry-regcred-web
